name: Fetch Parking Data

on:
  schedule:
    # 한국 06~08시 (UTC 21~23시 전날)
    - cron: "0,10,20,30,40,50 21-23 * * *"
    # 한국 09~24시 (UTC 0~15시 당일)
    - cron: "0,10,20,30,40,50 0-15 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run data fetch
        run: python fetch_parking.py

      - name: Commit & push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add parking_data/*.csv
          git commit -m "Update parking data" || echo "No changes to commit"
          git push origin main
